language: android
# sudo set to required because of an issue with how TravisCI handles builds in Docker containers https://github.com/travis-ci/travis-ci/issues/3695.
# Setting sudo to required prevents Travis from testing the project in a Docker container.
sudo: required
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repositor
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - echo ${ANDROID_HOME}
  - echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-29"
  - echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;29.0.3"
  - echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager "extras;android;m2repository"
  - echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager "extras;google;m2repository"
  - export LANG=en_US.UTF-8

before_cache:
  -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  -rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - chmod 755 gradlew
  - ls -la
  # Enable the line below once we get all the test passing, currently most of the tests are failing 
  # so we'll just if the project compiles
  - travis_wait ./gradlew clean --stacktrace
  #Run All tests Unit and Instrumentation
  - travis_wait ./gradlew :opensrp-growth-monitoring:jacocoTestReport --stacktrace
  - travis_wait ./gradlew :opensrp-growth-monitoring:coveralls --stacktrace

notifications:
  slack:
    secure: fAiZ4yA7DM6nUKh7nqsCTqZBb03VEAvi5NcRu5mNh5coNn/50XNeZl+qpv7Dw70Ef85Y/k68uc6KwTGVqPXEmVq9Hk3e7lqpBNN8rufvgCYDDGPmywBmU5BhSeykKo0Ee7llM3mRR/EipjIWw1+YvMcS3hCoygf/UlMDDhG0Jo0=